# Generated by Django 2.2.13 on 2020-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='best bikes for you', max_length=50)),
                ('telephone', models.CharField(default='99999999', max_length=8)),
                ('telephone2', models.CharField(default='99999999', max_length=8)),
                ('email', models.CharField(default='creto@gmail.com', max_length=50)),
                ('email2', models.CharField(default='rovadex@gmail.com', max_length=50)),
                ('address', models.CharField(default='Rovadex © 2020. All Rights Reserved', max_length=255)),
                ('date_cre', models.DateTimeField(auto_now_add=True)),
                ('date_mod', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Creto',
                'verbose_name_plural': 'Creto Informations',
            },
        ),
    ]
