# Generated by Django 2.2.13 on 2020-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reduction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
